#!/bin/bash
get_so(){
        while test -n "$1"
        do
        case $1 in
                -s | --operatingsystem)
                        grep PRETTY_NAME= /etc/os-release | cut -d \" -f 2 | awk '{print $1}'
                ;;
                -v | --version)
                        grep VERSION_ID= /etc/os-release | cut -d \" -f2
                ;;
                *) echo "opcao invalida"
        esac
        shift
        done
}

centos(){
	yum -y install http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
	yum -y install zabbix-agent
	
	sed -i "s/Server=127.0.0.1/Server=$zabbix_server/g" /etc/zabbix/zabbix_agentd.conf
	sed -i "s/ServerActive=127.0.0.1/ServerActive=$zabbix_server/g" /etc/zabbix/zabbix_agentd.conf
	sed -i "s/Hostname=Zabbix server/Hostname=$HOSTNAME/g" /etc/zabbix/zabbix_agentd.conf
	
	systemctl start zabbix-agent
	systemctl enable zabbix-agent
}

debian(){
	wget http://repo.zabbix.com/zabbix/3.4/debian/pool/main/z/zabbix-release/zabbix-release_3.4-1+stretch_all.deb
	dpkg -i zabbix-release_3.4-1+stretch_all.deb
	apt update
	apt-get install zabbix-agent -y
}

ubuntu(){
	wget http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb
	dpkg -i zabbix-release_3.4-1+xenial_all.deb
	apt update
	apt-get install zabbix-agent -y
}

case `get_so -s` in
        elementary|Debian) debian ;;
	Ubuntu) ubuntu ;;
        CentOS) centos ;;
        Red) centos ;;
esac
