#!/bin/bash
echo "deb http://deb.theforeman.org/ trusty 1.12" > /etc/apt/sources.list.d/foreman.list
echo "deb http://deb.theforeman.org/ plugins 1.12" >> /etc/apt/sources.list.d/foreman.list
apt-get update
export DEBIAN_FRONTEND=noninteractive
apt-get -qq -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold" \
    --assume-yes --only-upgrade install ruby\* foreman\* -y
foreman-rake db:migrate
foreman-rake db:seed
foreman-rake tmp:cache:clear
foreman-rake tmp:sessions:clear
apt-get install foreman-openstack -y
foreman-installer --noop --dont-save-answers --verbose
foreman-installer
apt upgrade -y
apt-get clean all
