#!/bin/bash
<% subnet = @host.subnet -%>

<% if subnet.respond_to?(:dhcp_boot_mode?) -%>
<% dhcp = subnet.dhcp_boot_mode? && !@static -%>
<% else -%>
<% dhcp = !@static -%>
<% end -%>

echo 'root:<%= root_pass -%>' | /usr/sbin/chpasswd -e

<% unless dhcp -%>
/bin/sed -i "s/^search.*$/search <%= @host.domain %>/g" /etc/resolv.conf
/bin/sed -i "s/.*dns-search.*/\tdns-search <%= @host.domain %>/g" /etc/network/interfaces
<% end -%>

/bin/sed -i "s/^<%= @host.ip %>.*/<%= @host.ip %>\t<%= @host.shortname %>.<%= @host.domain %>\t<%= @host.shortname %>/g" /etc/hosts

echo "192.168.22.12 puppet.local" >> /etc/hosts
echo "192.168.111.90 foreman.local" >> /etc/hosts
/bin/echo <%= @host.shortname %>.<%= @host.domain %> > /etc/hostname

hostnamectl set-hostname <%= @host.shortname %>.<%= @host.domain %>

<%= snippet 'puppet_setup' %>
<%= snippet 'preseed_networking_setup' %>

<%= snippet('remote_execution_ssh_keys') %>
<%= snippet('remote_ssh') %>

/usr/bin/wget --no-proxy --quiet --output-document=/dev/null --no-check-certificate <%= foreman_url('built') %>
sync
sleep 5
/bin/systemctl enable puppet
/bin/systemctl start puppet
exit 0
